#ifndef PEONY_EMBLEM_PLUGIN_GLOBAL_H
#define PEONY_EMBLEM_PLUGIN_GLOBAL_H

#include <QtGlobal>

#if defined(EMBLEM_LIBRARY)
#  define EMBLEMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define EMBLEMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PEONY_EMBLEM_PLUGIN_GLOBAL_H
